### ISSUE TITLE
user-by/id data & form data seem to be combined

### ISSUE THREAD

**Issue by claudiu-apetrei** [awkay/untangled-template#2]
Don't know if it's by design. But both user & new-user seem to have the same Ident.

```
cljs.user=> (log-app-state :user/by-id)
#:user{:by-id
       {#om/id["b1278b61-7871-4d99-b1be-a7fec0fbbbae"]
        {:uid #om/id["b1278b61-7871-4d99-b1be-a7fec0fbbbae"],
         :name "",
         :password "",
         :password2 "",
         :email "",
         :untangled.ui.forms/form
         {:on-form-change
          #:on-form-change{:mutation-symbol
                           untangled-template.ui.new-user/check-passwords-match},
         .....
         :untangled.client.impl.om-plumbing/not-found {}}}
```

**Comment by awkay** [comment]
Intentional. It's just the table for user data.

**Comment by claudiu-apetrei** [comment]
@awkay Trying to get my head around the benefits/trade-offs of this approach.
Haven't had time to look into forms that much but seems very similar with a react-redux project that I know http://redux-form.com/6.8.0/. 

This caught my attention the first thing I did after opening the page in browser was to do a log-app-state to get a overview of the app-state and this added a lot of noise.

Not sure about how this scales. Let's say I have a articles/by-id with 10 articles & a new article form. When debugging listing looking at the state and seeing 10articles + the form internals seems like a bit of a inconvenience (especially given the verbosity of form data). Also having a lot of forms with this approach makes it pretty hard to filter out all in log-app-state. 

The approach redux-forms takes (not exactly sure how to map this nicely to untangled) all forms store there data inside a key: {:forms {}}. And there it stores all of it's internals & the current state of the form, it will get into the other parts of the state when clicking submit.

**Comment by awkay** [comment]
Noted. This would probably be better as an enhancement request issue on untangled itself.
